name: hi
on: push
jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - run: pwd;date;ls /home
      - uses: actions/checkout@v4
      - name: Slack 성공 알림
        if: success()
        run: |
          curl -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
            -H "Content-type: application/json" \
            --data "{
              \"channel\": \"#jenkins-deploy-notice\",
              \"text\": \"✅ 배포 성공!\"
              }"

      - name: Slack 실패 알림
        if: failure()
        run: |
          curl -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
            -H "Content-type: application/json" \
            --data "{
              \"channel\": \"#jenkins-deploy-notice\",
              \"text\": \"❌ 배포 실패!\"
              }"